#!/bin/bash

DEBUG=0

# determines which Mesos image is chosen
MESOS_VERSION=0.18.2
NAMESERVER_IMAGE="rogaha/dnsmasq-precise"

# set this value to the number of workers you want
NUM_WORKERS=3

if [[ "$USER" != "root" ]]; then
   echo "please run as: sudo $0"
   exit 1
fi

source ../../deploy/start_nameserver.sh
source start_mesos_cluster.sh

echo "*** Starting Mesos $MESOS_VERSION ***"
start_nameserver $NAMESERVER_IMAGE
wait_for_nameserver
start_mesos_master
sleep 5
start_mesos_workers
sleep 3
print_cluster_info

