# Shark master
FROM rogaha/shark-base:0.9.1

MAINTAINER Roberto G. Hashioka "roberto_hashioka@hotmail.com"

# Add run script
ADD files /root/shark_shell_files

# Add default command for master
ENTRYPOINT ["/root/shark_shell_files/default_cmd"]

