# Shark master
FROM rogaha/shark-base:0.9.1

MAINTAINER Roberto G. Hashioka "roberto_hashioka@hotmail.com"

# Add run script
ADD files /root/shark_master_files

# Add default command for master
CMD ["/root/shark_master_files/default_cmd"]

