# Mesos
FROM rogaha/mesos-base:0.18.2

MAINTAINER Roberto G. Hashioka "roberto_hashioka@hotmail.com"

# Setup a volume for data
#VOLUME ["/data"]

ADD files /root/mesos_master_files

CMD ["/root/mesos_master_files/default_cmd"]
